<?php

namespace Database\Seeders;

use App\Enum\InventoryTypeEnum;
use App\Models\Inventory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\InventoryType;


class InventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $types = [
            [
                'name' => 'Medicine',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Medical Supplies',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Medical Equipment',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        InventoryType::insert($types);

        $inventories = [
            [
                'item_name' => 'Paracetamol',
                'item_code' => 'MC0000001',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 100,
                'price' => 10,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Atorvastatin',
                'item_code' => 'MC0000002',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 100,
                'price' => 5,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Salbutamol',
                'item_code' => 'MC0000003',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 100,
                'price' => 15,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Metformin',
                'item_code' => 'MC0000004',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 100,
                'price' => 15,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Amoxicillin',
                'item_code' => 'MC0000005',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 100,
                'price' => 15,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Ibuprofen',
                'item_code' => 'MC0000006',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 120,
                'price' => 12,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Lisinopril',
                'item_code' => 'MC0000007',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 150,
                'price' => 10,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Amlodipine',
                'item_code' => 'MC0000008',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 130,
                'price' => 8,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Ciprofloxacin',
                'item_code' => 'MC0000009',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 90,
                'price' => 14,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Prednisone',
                'item_code' => 'MC0000010',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 110,
                'price' => 20,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Omeprazole',
                'item_code' => 'MC0000011',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 140,
                'price' => 13,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Simvastatin',
                'item_code' => 'MC0000012',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 100,
                'price' => 18,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Metoprolol',
                'item_code' => 'MC0000013',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 160,
                'price' => 17,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Cetirizine',
                'item_code' => 'MC0000014',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 200,
                'price' => 7,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Additional 20 items
            [
                'item_name' => 'Losartan',
                'item_code' => 'MC0000015',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 150,
                'price' => 12,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Gabapentin',
                'item_code' => 'MC0000016',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 180,
                'price' => 11,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Warfarin',
                'item_code' => 'MC0000017',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 200,
                'price' => 22,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Furosemide',
                'item_code' => 'MC0000018',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 130,
                'price' => 14,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Dexamethasone',
                'item_code' => 'MC0000019',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 90,
                'price' => 18,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Acetaminophen',
                'item_code' => 'MC0000020',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 220,
                'price' => 8,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Fluoxetine',
                'item_code' => 'MC0000021',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 140,
                'price' => 19,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Clonazepam',
                'item_code' => 'MC0000022',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 150,
                'price' => 15,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Alprazolam',
                'item_code' => 'MC0000023',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 200,
                'price' => 14,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Hydrochlorothiazide',
                'item_code' => 'MC0000024',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 110,
                'price' => 13,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Captopril',
                'item_code' => 'MC0000025',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 130,
                'price' => 16,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Bupropion',
                'item_code' => 'MC0000026',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 140,
                'price' => 20,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Loratadine',
                'item_code' => 'MC0000027',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 170,
                'price' => 9,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Ceftriaxone',
                'item_code' => 'MC0000028',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 80,
                'price' => 25,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Ranitidine',
                'item_code' => 'MC0000029',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 120,
                'price' => 12,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Sildenafil',
                'item_code' => 'MC0000030',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 90,
                'price' => 30,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Lidocaine',
                'item_code' => 'MC0000031',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 100,
                'price' => 17,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Methylprednisolone',
                'item_code' => 'MC0000032',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 80,
                'price' => 22,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_name' => 'Duloxetine',
                'item_code' => 'MC0000033',
                'type_id' => InventoryTypeEnum::Medicine,
                'quantity' => 150,
                'price' => 16,
                'manage_by'=> 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Inventory::insert($inventories);

    }
}
